<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ArtSync.Abstractions\ArtSync.Abstractions.csproj" />
    <ProjectReference Include="..\ArtSync.Compat\ArtSync.Compat.csproj" />
    <ProjectReference Include="..\ArtSync.Schema\ArtSync.Schema.csproj" />
    <ProjectReference Include="..\ArtSync.Data\ArtSync.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
