#!/usr/bin/env bash
# Provision rg-artsync + Azure SQL (serverless) and write repo-root .env
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

if [[ -f "$ENV_FILE" ]]; then
    set +H
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
fi

RG="${ARTSYNC_RESOURCE_GROUP:-rg-artsync}"
LOC="${ARTSYNC_LOCATION:-westus2}"
ADMIN="${ARTSYNC_SQL_ADMIN:-artsyncadmin}"
DB_NAME="${ARTSYNC_AZURE_DB:-MARS}"

sql_location_available() {
    local loc="$1"
    az rest --method get \
        --url "https://management.azure.com/subscriptions/$(az account show --query id -o tsv)/providers/Microsoft.Sql/locations/${loc}/capabilities?api-version=2023-08-01-preview" \
        --query status -o tsv 2>/dev/null | grep -qx Available
}

if ! sql_location_available "$LOC"; then
    echo "==> SQL provisioning not available in $LOC; trying westus2 / centralus / southcentralus…"
    LOC=""
    for cand in westus2 centralus southcentralus westus westus3 westeurope uksouth; do
        if sql_location_available "$cand"; then
            LOC="$cand"
            break
        fi
    done
    if [[ -z "$LOC" ]]; then
        echo "ERROR: no Azure SQL region available on this subscription." >&2
        exit 1
    fi
fi

PASS="${ARTSYNC_SQL_PASSWORD:-}"
if [[ -z "$PASS" ]]; then
    PASS="ArtSync_Lab_$(openssl rand -hex 10)!"
fi

IP="$(curl -sS --max-time 15 https://api.ipify.org)"
if [[ ! "$IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "ERROR: could not detect public IPv4 (got: $IP)" >&2
    exit 1
fi

echo "==> Subscription: $(az account show --query name -o tsv)"
echo "==> Resource group: $RG"
echo "==> SQL location: $LOC"
echo "==> Client IP: $IP"

if [[ "$(az group exists --name "$RG")" == "true" ]]; then
    echo "==> Resource group $RG already exists ($(az group show -n "$RG" --query location -o tsv))"
else
    az group create --name "$RG" --location "$LOC" --tags project=artsync purpose=lab >/dev/null
fi

echo "==> Deploying Azure SQL (serverless GP_S_Gen5_1)…"
OUT_JSON="$(az deployment group create \
    --resource-group "$RG" \
    --template-file "$REPO_ROOT/infra/main.bicep" \
    --parameters \
        location="$LOC" \
        administratorLogin="$ADMIN" \
        administratorLoginPassword="$PASS" \
        clientIpv4="$IP" \
        databaseName="$DB_NAME" \
    --query properties.outputs \
    --output json)"

FQDN="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["sqlServerFqdn"]["value"])' <<<"$OUT_JSON")"
SERVER="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["sqlServerName"]["value"])' <<<"$OUT_JSON")"

SRC_CS="Server=$FQDN,1433;Database=$DB_NAME;User ID=$ADMIN;Password=$PASS;Encrypt=True;TrustServerCertificate=False;Connection Timeout=60"
TGT_CS="Server=localhost,1433;Database=MARS;User ID=sa;Password=ArtSync_Test@2026;TrustServerCertificate=True;Connection Timeout=30"

export RG LOC ADMIN PASS FQDN DB_NAME SRC_CS TGT_CS
umask 077
python3 - "$ENV_FILE" <<'PY'
import json, os, sys
path = sys.argv[1]
pairs = [
    ("ARTSYNC_RESOURCE_GROUP", os.environ["RG"]),
    ("ARTSYNC_LOCATION", os.environ["LOC"]),
    ("ARTSYNC_SQL_ADMIN", os.environ["ADMIN"]),
    ("ARTSYNC_SQL_PASSWORD", os.environ["PASS"]),
    ("ARTSYNC_AZURE_SERVER", os.environ["FQDN"]),
    ("ARTSYNC_AZURE_DB", os.environ["DB_NAME"]),
    ("ARTSYNC_LOCAL_SERVER", "localhost,1433"),
    ("ARTSYNC_LOCAL_DB", "MARS"),
    ("ARTSYNC_LOCAL_USER", "sa"),
    ("ARTSYNC_LOCAL_PASSWORD", "ArtSync_Test@2026"),
    ("ARTSYNC_SRC_CS", os.environ["SRC_CS"]),
    ("ARTSYNC_TGT_CS", os.environ["TGT_CS"]),
]
with open(path, "w") as f:
    f.write("# Generated by scripts/lab-azure.sh — do not commit\n")
    for k, v in pairs:
        f.write(f"{k}={json.dumps(v)}\n")
os.chmod(path, 0o600)
PY

echo "==> Wrote $ENV_FILE"
echo "==> Azure SQL: $SERVER / $FQDN / $DB_NAME"
echo "==> Local target: localhost,1433 / MARS (after ./scripts/lab-up.sh)"
echo
echo "Next: ./scripts/lab-up.sh   # restore the .bak locally"
echo "Then: source .env and run ArtSync Azure → local (compare-only first)."
